# Generated by Django 2.2.5 on 2020-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200523_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='describtion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
