# Generated by Django 2.2.5 on 2020-05-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200525_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facilites',
            new_name='facilities',
        ),
    ]
