# Generated by Django 2.2.5 on 2020-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200606_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Room Type'},
        ),
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(),
        ),
    ]
